use std::str::FromStr;

use bitcoincore_rpc::{Auth, Client, RpcApi};

use serde_json::Value;

use simplicityhl::elements::encode::serialize_hex;
use simplicityhl::elements::{Address, AssetId, BlockHash, Transaction, Txid};
use simplicityhl::simplicity::bitcoin;

use super::error::RpcError;

use crate::utils::sat2btc;

/// A lightweight wrapper around the standard `bitcoincore_rpc` `Client` providing Elements-specific functionality.
#[derive(Debug)]
pub struct ElementsRpc {
    /// The underlying JSON-RPC client connected to the Elements node.
    pub inner: Client,
    /// The authentication credentials used.
    pub auth: Auth,
    /// The URL endpoint of the node.
    pub url: String,
}

impl ElementsRpc {
    /// Creates a new `ElementsRpc` client.
    ///
    /// # Errors
    /// Returns an `RpcError` if it fails to initialize the connection or if a liveness `ping` fails.
    pub fn new(url: String, auth: Auth) -> Result<Self, RpcError> {
        let inner = Client::new(url.as_str(), auth.clone())?;
        inner.ping()?;

        Ok(Self { inner, auth, url })
    }

    /// Requests a new wallet address from the node, mapped to the provided label.
    ///
    /// # Errors
    /// Returns an `RpcError` if the node fails to generate an address or yields an invalid string payload.
    ///
    /// # Panics
    /// Panics if the returned JSON value is not a string, or if the string cannot be parsed into a valid `Address`.
    pub fn get_new_address(&self, label: &str) -> Result<Address, RpcError> {
        const METHOD: &str = "getnewaddress";

        let addr: Value = self.inner.call(METHOD, &[label.into(), "bech32".to_string().into()])?;

        Ok(Address::from_str(addr.as_str().unwrap()).unwrap())
    }

    /// Instructs the node to transfer funds directly to the target address.
    ///
    /// # Errors
    /// Returns an `RpcError` if the node returns an error or returns an invalid `Txid` payload.
    ///
    /// # Panics
    /// Panics if the satoshi amount cannot be converted to a valid BTC amount, if the returned
    ///  JSON value is not a string, or if the string cannot be parsed into a valid `Txid`.
    pub fn send_to_address(&self, address: &Address, satoshi: u64, asset: Option<AssetId>) -> Result<Txid, RpcError> {
        const METHOD: &str = "sendtoaddress";

        let btc = sat2btc(satoshi);
        let btc = bitcoin::amount::Amount::from_btc(btc)
            .unwrap()
            .to_string_in(bitcoin::amount::Denomination::Bitcoin);

        let r = match asset {
            Some(asset) => self.inner.call::<Value>(
                METHOD,
                &[
                    address.to_string().into(),
                    btc.into(),
                    "".into(),
                    "".into(),
                    false.into(),
                    false.into(),
                    1.into(),
                    "UNSET".into(),
                    false.into(),
                    asset.to_string().into(),
                ],
            )?,
            None => self
                .inner
                .call::<Value>(METHOD, &[address.to_string().into(), btc.into()])?,
        };

        Ok(Txid::from_str(r.as_str().unwrap()).unwrap())
    }

    /// Instructs the node to rescan the block chain for missed wallet transactions.
    ///
    /// # Errors
    /// Returns an `RpcError` if the node fails the RPC call.
    pub fn rescan_blockchain(&self, start: Option<u64>, stop: Option<u64>) -> Result<(), RpcError> {
        const METHOD: &str = "rescanblockchain";

        let mut args = Vec::with_capacity(2);

        if start.is_some() {
            args.push(start.into());
        }

        if stop.is_some() {
            args.push(stop.into());
        }

        self.inner.call::<Value>(METHOD, &args)?;

        Ok(())
    }

    /// Mines a specified number of new blocks mapping generated rewards to a newly generated wallet address.
    ///
    /// # Errors
    /// Returns an `RpcError` if generating the address or calling the `generatetoaddress` RPC command fails.
    pub fn generate_blocks(&self, block_num: u64) -> Result<(), RpcError> {
        const METHOD: &str = "generatetoaddress";

        let address = self.get_new_address("")?.to_string();
        self.inner.call::<Value>(METHOD, &[block_num.into(), address.into()])?;

        Ok(())
    }

    /// Instructs the node to sweep the `initialfreecoins` balance generated by standard regtest genesis blocks.
    ///
    /// # Errors
    /// Returns an `RpcError` if the `getnewaddress` or `sendtoaddress` RPC commands fail.
    pub fn sweep_initialfreecoins(&self) -> Result<(), RpcError> {
        const METHOD: &str = "sendtoaddress";

        let address = self.get_new_address("")?;
        self.inner.call::<Value>(
            METHOD,
            &[
                address.to_string().into(),
                "21".into(),
                "".into(),
                "".into(),
                true.into(),
            ],
        )?;

        Ok(())
    }

    /// Reads the chain the node runs: its genesis block hash and its policy asset.
    ///
    /// # Errors
    /// Returns an `RpcError` if a call fails or returns something that does not parse.
    pub fn chain_identity(&self) -> Result<(BlockHash, AssetId), RpcError> {
        let genesis: String = self.inner.call("getblockhash", &[0.into()])?;
        let info: Value = self.inner.call("getsidechaininfo", &[])?;
        let policy = info["pegged_asset"]
            .as_str()
            .ok_or_else(|| RpcError::ElementsRpcUnexpectedReturn("getsidechaininfo".into()))?;

        let genesis =
            BlockHash::from_str(&genesis).map_err(|_| RpcError::ElementsRpcUnexpectedReturn("getblockhash".into()))?;
        let policy =
            AssetId::from_str(policy).map_err(|_| RpcError::ElementsRpcUnexpectedReturn("getsidechaininfo".into()))?;

        Ok((genesis, policy))
    }

    /// Asks the node whether its mempool would accept `tx`, without broadcasting it.
    ///
    /// Returns `Ok(Ok(()))` when it would, and `Ok(Err(reason))` with the node's reason when not.
    ///
    /// # Errors
    /// Returns an `RpcError` if the call fails or its answer does not parse.
    pub fn test_mempool_accept(&self, tx: &Transaction) -> Result<Result<(), String>, RpcError> {
        const METHOD: &str = "testmempoolaccept";

        let answer: Value = self.inner.call(METHOD, &[vec![serialize_hex(tx)].into()])?;
        let verdict = answer
            .get(0)
            .ok_or_else(|| RpcError::ElementsRpcUnexpectedReturn(METHOD.into()))?;

        if verdict["allowed"].as_bool() == Some(true) {
            return Ok(Ok(()));
        }

        Ok(Err(verdict["reject-reason"].as_str().unwrap_or("rejected").to_string()))
    }

    /// Mines one block holding exactly `txs`, in order, whatever the mempool holds. A transaction
    /// the mempool's policy would refuse goes in all the same, so a block tests consensus alone.
    ///
    /// Returns `Ok(Ok(hash))` for a block the node accepted, and `Ok(Err(message))` with the
    /// node's message for one it refused.
    ///
    /// # Errors
    /// Returns an `RpcError` if the call fails for any other reason.
    pub fn generate_block_with(&self, txs: &[Transaction]) -> Result<Result<BlockHash, String>, RpcError> {
        const METHOD: &str = "generateblock";

        let address = self.get_new_address("")?.to_string();
        let raw: Vec<String> = txs.iter().map(serialize_hex).collect();

        match self.inner.call::<Value>(METHOD, &[address.into(), raw.into()]) {
            Ok(answer) => {
                let hash = answer["hash"]
                    .as_str()
                    .and_then(|hash| BlockHash::from_str(hash).ok())
                    .ok_or_else(|| RpcError::ElementsRpcUnexpectedReturn(METHOD.into()))?;

                Ok(Ok(hash))
            }
            Err(bitcoincore_rpc::Error::JsonRpc(bitcoincore_rpc::jsonrpc::Error::Rpc(error))) => {
                Ok(Err(format!("{} (code {})", error.message, error.code)))
            }
            Err(error) => Err(error.into()),
        }
    }

    /// The weight the node reports for a transaction it knows, and the block it is in, if any.
    ///
    /// # Errors
    /// Returns an `RpcError` if the node does not know the transaction or the answer does not parse.
    pub fn transaction_weight(&self, txid: &Txid) -> Result<(u64, Option<BlockHash>), RpcError> {
        const METHOD: &str = "getrawtransaction";

        let answer: Value = self.inner.call(METHOD, &[txid.to_string().into(), true.into()])?;
        let weight = answer["weight"]
            .as_u64()
            .ok_or_else(|| RpcError::ElementsRpcUnexpectedReturn(METHOD.into()))?;
        let block = answer["blockhash"]
            .as_str()
            .and_then(|hash| BlockHash::from_str(hash).ok());

        Ok((weight, block))
    }

    /// Retrieves the current block chain tip height.
    ///
    /// # Errors
    /// Returns an `RpcError` if the node call fails or yields a JSON structure that does not map successfully to a `u64`.
    pub fn height(&self) -> Result<u64, RpcError> {
        const METHOD: &str = "getblockcount";

        self.inner
            .call::<serde_json::Value>(METHOD, &[])?
            .as_u64()
            .ok_or_else(|| RpcError::ElementsRpcUnexpectedReturn(METHOD.into()))
    }
}
